version: '3.9'

services:

  tofi_bank_app:
    container_name: tofi_bank_app
    build: .
    volumes: 
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_DB=postgres
      - PG_HOST=db
      - PG_PORT=5432
    depends_on:
      - tofi_db

  tofi_db:
    container_name: tofi_db
    image: postgres:12
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data 

volumes:
  pgdata: {} 
